services:
  pg:
    image: "${IMAGE_REGISTRY_BASE_URL}/postgis/postgis:14-3.2"
    restart: "always"
    ports:
      - "${ALCHEMYPDF_DB_PORT}:${ALCHEMYPDF_DB_PORT}"
    healthcheck:
      test: "pg_isready --username=${ALCHEMYPDF_DB_USERNAME} && psql --username=${ALCHEMYPDF_DB_USERNAME} --list"
      timeout: 10s
      retries: 20
    environment:
      POSTGRES_USER: "${ALCHEMYPDF_DB_USERNAME}"
      POSTGRES_PASSWORD: "${ALCHEMYPDF_DB_PASSWORD}"

  db:
    network_mode: "host"
    depends_on:
      pg:
        condition: service_healthy
    build:
      context: "./"
      dockerfile: "Dockerfile"
      args:
        IMAGE_REGISTRY_BASE_URL: ${IMAGE_REGISTRY_BASE_URL}
    env_file:
      - .env
